name: Build

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            aes

      - name: Build with Makefile
        run: make

      - name: Build with Test file
        run: |
          python3 -c "import sys; sys.path.append('./aes'); from aes import sub_bytes, bytes2matrix"
          python3 ctypes_test.py
